### ISSUE TITLE
Fiducials code tries to run raspicam even in gazebo

### ISSUE THREAD

**Issue by maryamnassar** [UbiquityRobotics/magni_robot#120]

**Comment by tp4348** [comment]
@maryamnassar please give a bit of more insight what are you struggling with.

**Comment by MoffKalast** [comment]
I'm pretty sure he means that the fiducial slam/follow launch file also starts up raspicam_node. There should probably be separate launch files for gazebo and real robots.

**Comment by JanezCim** [comment]
@maryamnassar, @rohbotics or @MoffKalast  can anyone tell me how to reproduce this problem? Running `roslaunch magni_gazebo fiducial_world.launch` I do not encounter any problem. I am doing this on branch `indigo-devel`
