### ISSUE TITLE
SSH login problem 

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/magni_robot#124]
the root of the problem was that the ssh keys in /etc/ssh, which are used for the ssh server, were all empty -- zero-size files.  I removed all the zero-sized files like this:

# /bin/rm -v /etc/ssh/ssh_host_* 

and then I generated new ssh keys like this:
 
dpkg-reconfigure openssh-server

After this, I restarted the ssh server:

sudo systemctl restart ssh

And ssh into the robot's pi now works fine.  

So this seems to be an error on Ubiquity's part:  you shipped a robot with empty ssh keys in /etc/ssh

**Comment by rohbotics** [comment]
Copying from the email I sent to the customer:


> Thanks for the detailed information, we have not seen this error before.
> 
> The /etc/ssh/ssh_host_* keys are created on the first boot of the SD card, which will be when you turn it on for the first time.
> It is possible that a power interruption during the first boot caused this process to be interrupted in a way that caused the 0 length keys.
> 
> Glad that you have resolved the issue for now, and can continue making progress.
> Sorry for any frustration.
