### ISSUE TITLE
Update URDF for Magni V5

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/magni_robot#14]
Needs to have both a URDF and visual meshes to go along with it

**Comment by rohbotics** [comment]
Definition of Done:

The URDF reflects the actual physical form of Magni V5 (Blue ones).

**Comment by davecrawley** [comment]
Note - that the new Magni V5 (blue ones) have some slight physical differences to the previous iteration. I have step and solidworks models of the new version. Let me know how I get these in to the URDF.

**Comment by rohbotics** [comment]
@davecrawley Are we still holding on the animators new 3d models?

**Comment by davecrawley** [comment]
- [ ] Camera Positions
- [ ] Sonar Positions
- [ ] Wheel positions
- [ ] 3-D sensor positions
- [ ] Height of center point axles off ground
- [x] Set footprint params in `move_basic.launch`

**Comment by jim-v** [comment]
It would be good if we can flip the image so that it is upright.  This affects the camera orientation, and needs to be tested on the actual hardware.

**Comment by rohbotics** [comment]
solved with #56 i believe
