### ISSUE TITLE
magni_description description.launch

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/magni_robot#142]
` <node name="robot_state_publisher" pkg="robot_state_publisher" type="state_publisher" />`

The last Line needs to be changed to:

` <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" />`

In order to work in Melodic and Noetic - generates a warning or fails to render model correctly in rviz/gazebo.

For some reason, I can't create my own pull request.

**Comment by MoffKalast** [comment]
Oh wow, this may be a thing in kinetic as well. I've had that annoying issue happen on one of my installations but figured I set something up wrong. I'll run a short test and make the change if it works fine on kinetic as well.

**Comment by MoffKalast** [comment]
Hmm, well it doesn't fix that specific issue but at least I can confirm that it makes no difference in kinetic. I'll make a PR.

**Comment by MoffKalast** [comment]
Actually, let me set this as closed by the PR itself when it's merged.
