### ISSUE TITLE
Magni falling over in Gazebo

### ISSUE THREAD

**Issue by dorkamotorka** [UbiquityRobotics/magni_robot#151]
@anfederman reported Magni in Gazebo is falling over onto the face when stopping. I think this is only the case for Melodic and Noetic where the simulation got "a bit more real".

**Comment by anfederman** [comment]
Has this been fixed now?  I think there is a pull request pending, if so we can close.

**Comment by MoffKalast** [comment]
Yes, there's #157 but I still have to test it out on kinetic if everything's fine before we call it good, just so we don't break all of our existing projects prematurely. I'm not sure if the fix is backwards compatible or not yet.

**Comment by MoffKalast** [comment]
Closed by #157

**Comment by anfederman** [comment]
So a pull of magni_robotb will fix?

**Comment by anfederman** [comment]
I just tested and it appears fixed.
