### ISSUE TITLE
Old PRs in magni_robot repo that need to be resolved

### ISSUE THREAD

**Issue by MoffKalast** [UbiquityRobotics/magni_robot#154]
- Feature corelaunch rewrite
- Max linear velocity increased to 1.1m/s
- Motion vectors in gazebo
- Adding support for nav2D flat nav. Adding some existing ROS params to…

**Comment by JanezCim** [comment]
> Camera Gazebo sensor link confusion elimination

solves

> Implemented quickfix suggestion in #140

So the #140 thing is not needed on your list
