### ISSUE TITLE
Magni needs OLED node to come up by default on image and be included in apt upgrade

### ISSUE THREAD

**Issue by mjstn** [UbiquityRobotics/magni_robot#155]
As title says we need these two things for the Magni product line (includes breadcrumb but Magni robot is #1 priority)

1. get to Jenny in production proper images that have current OLED display actually set to come up.  The node ignores display if not found.
2. have things so an 'apt upgrade' pulls in OLED display node as well as whatever launch changes are required so   'magni-base' service includes firing it up.

**Comment by anfederman** [comment]
This is already implemented in my SD image.   Changes were made to the /etc/ubiquity/robot.yaml   and /magni_robot/magni_bringup/ base launch.py   -  also  oled_display_node files.

**Comment by anfederman** [comment]
The only change needed (I think)  is to the robot.yaml file


ubuntu@magnitest:/etc/ubiquity$ more robot.yaml :+1: 
--------
# Robot Configuration

raspicam: {'position' : 'front'}

#sonars: None
sonars: 'pi_sonar_v1' # Use this to enable sonars

#OLED display

oled_display: {'controller' : 'SH1106'}

------

**Comment by MoffKalast** [comment]
Ok that's good to know, we should add that to the script that generates the yaml.
