### ISSUE TITLE
Python 3.8 issues

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/magni_robot#166]
I recently upgraded to 20.04 Noetic on an Acer (old Turtlebot laptop)  I had previously updated Python from 3.5/6 to 3.8 to run pygames on the unit.  I then installed noetic desktop full and rebuilt catkin with magni-robot.

I am having numerous Python issues with libraries not found and looking in the wrong paths.  Specifically numpy and shiboken2 aren't found on roslaunch, and hence magni-gazebo empty-world comes up with no cmd/vel odom or slider applet.  I fixed some things by adding /usr/lib/python3/ to the LIB path, but things are still painful.  Not sure if we should require certain python version or environment when releasing images.

Not sure who should look at this.

**Comment by rohbotics** [comment]
#167 fixes the launch related python3 bugs in the noetic-devel branch.
