### ISSUE TITLE
New launch_core doesn't work with old robot.yaml

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/magni_robot#172]
If someone just copies their old robot.yaml over, the new launch_core script may fail.

Old default yaml:
```
# Robot Configuration

raspicam: {'position' : 'upward'}

sonars: None
# sonars: 'pi_sonar_v1' # Use this to enable sonars
```

This errors on:
ERROR: 'camera_installed' entry was not found in conf['raspicam']

Expected behavior:
A missing key in the yaml should be replaced by the same key in the default yaml.

**Comment by JanezCim** [comment]
I see, good catch, will try to fix it!
