### ISSUE TITLE
Change Lidar location on Top plate

### ISSUE THREAD

**Issue by JanezCim** [UbiquityRobotics/magni_robot#184]
Zdej pa šeenkrat spremenjene želje ker so na sestanku včeraj ljudje želeli malo drugačno postavitev ekrana in lidarja na magni-ju:

dodatne info:
 - ekran je centralno poravnan
 - za inštalacijo ekrana bomo uporabili m3 standoffe tako da bi bile lokacije lukenj malo drugačne - na sliki
 - lidar luknje ostanejo isto razporejene med seboj, samo lidar lokacija bi se spremenila, tako da pride malo bolj nazaj (tako da lidar ne ovira vijakov za prišravfat top plate na robota) in malo na stran (tako da če hočjo ljudje na center kaj monterat da ševedno lahko)
 - ko se odločiš za natančno lokacijo lidarja nam prosim povej mere x, y na sliki magnicable

Rabiš še kaj informacij?
![magnicable](https://user-images.githubusercontent.com/8426792/135620849-557ab836-20e8-4202-8db9-be2b84251067.png)

![drawing](https://user-images.githubusercontent.com/8426792/135620905-6b0c7270-47d6-4894-9830-117a76b7fbe8.png)

**Comment by AljazKrsnik** [comment]
Hello

**Comment by JanezCim** [comment]
Hey @AljazKrsnik  how is this going?  :)

**Comment by AljazKrsnik** [comment]
![sestav lider lokacija](https://user-images.githubusercontent.com/87651656/136256179-b93dc676-32d6-44e6-9aa4-817327c046db.PNG)

**Comment by JanezCim** [comment]
Nice! Please can you give me the measures of the lidar x,y like its shown on the first picture? Also I forgot to mention, please also delete the square hole on the top plate, we dont need that anymore

**Comment by AljazKrsnik** [comment]
[TOP plate - added Lidar holes V_1.PDF](https://github.com/UbiquityRobotics/magni_robot/files/7324396/TOP.plate.-.added.Lidar.holes.V_1.PDF)

**Comment by AljazKrsnik** [comment]
Posiljam top plate brez izpranitve. Mislm, da je pozicija liderja dobro
definirana v x in y. Če pa rabiš dodatno kaj oz. nisem razumel pa povej.
Lp Aljaž

V V čet., 7. okt. 2021 ob 10:28 je oseba Janez Cimerman <
***@***.***> napisala:

**Comment by JanezCim** [comment]
Okay I see it now, thats ok, can you also attach the 3d file without the square hole and then we can close this :
![wohole](https://user-images.githubusercontent.com/8426792/136910648-1e2e11d4-5e85-46ed-a0d3-25b565da928c.png)
)

**Comment by AljazKrsnik** [comment]
File ki sem ti ga poslal, je že brez te luknje. Lp

V V tor., 12. okt. 2021 ob 09:24 je oseba Janez Cimerman <
***@***.***> napisala:

**Comment by mjstn** [comment]
I would like to request that posts to the issues be first translated with google translate or something so we maintain issue comments in English please.    I am unable to follow this issue as it stands.   Thank you for helping me.

**Comment by AljazKrsnik** [comment]
Ow sory. Conversation will continue in english from now on.


V V sre., 13. okt. 2021 ob 09:28 je oseba Mark Johnston <
***@***.***> napisala:

**Comment by JanezCim** [comment]
yes, and @AljazKrsnik this needs to become part of the default magni model on zoho. Then we can close this issue

**Comment by JanezCim** [comment]
![standoffs](https://user-images.githubusercontent.com/8426792/137465350-9bf544d2-337e-407f-8683-2e189a1bee2d.png)

**Comment by AljazKrsnik** [comment]
Consider it done

V V pet., 15. okt. 2021 ob 11:27 je oseba Janez Cimerman <
***@***.***> napisala:

**Comment by JanezCim** [comment]
yes, i've taken a look into this again and the screen holes actually should not have screw inserts Because the screen itself has a threaded hole. So the standoff would have to be screwed with a separate M3 screw from the bottom of the top plate
![standoofffs](https://user-images.githubusercontent.com/8426792/137478213-09f424cb-aadd-4837-b154-03e3d3ae73ab.png)

**Comment by JanezCim** [comment]
Please @MihaJelencic cut the top plate I sent to you on pvt with laser cutter and try to bolt it to the magni robot. Then place on top of it the ls lidar and a screen. We would just like to double check if all the holes on the new design of the top plate are fitting, before we produce houndrets of them. You dont have to screw on the lidar but i would like to ask you if you could do that with the screen. After that please tell us if everything fits, maybe post a pic of it here.

**Comment by MihaJelencic** [comment]
![20211028_095402](https://user-images.githubusercontent.com/76433738/139212229-93adb0f8-fb40-4086-be8a-2d86921705e0.jpg)
![20211028_095339](https://user-images.githubusercontent.com/76433738/139212241-c5bb54cf-e32b-44d3-96dc-4710a69f4e53.jpg)
Everything seems to fit

**Comment by JanezCim** [comment]
Cool, thank you!

**Comment by anfederman** [comment]
Could you also publish the x y z relative to base link and base footprint
of the holes on the top plate. This for figuring out description files for
other lidar like the LD06

**Comment by JanezCim** [comment]
True, @AljazKrsnik on your measures pdf i could not find these measures, can you provide them?
![lidarmeasures](https://user-images.githubusercontent.com/8426792/140499585-ceaa48a4-30e5-4a56-9a10-dacc0bfe343a.png)

**Comment by JanezCim** [comment]
for future reference on last image x: -0.092m, y: -0.066m

**Comment by AljazKrsnik** [comment]
Hi. Is this still an issue or is it solved?

**Comment by JanezCim** [comment]
@AljazKrsnik this model has been tested like described above and i think thats fine. If its part of our default magni 3d model, then this is solved.
