### ISSUE TITLE
LS Lidar temporary mechanical mount extention

### ISSUE THREAD

**Issue by JanezCim** [UbiquityRobotics/magni_robot#186]
We need to make a LSlidar mount extention board that will be a temporary solution before top plates get into production with standard magni. Confinements:
 - small board that will mount the LS lidar onto the magni base robot
 - small enough to fit into the box with lidar - with which it will be shipped
 - ideally lidar would be in the same side position as it is on the new top plate

**Comment by JanezCim** [comment]
The inside edge of the box the Lidar is packed in is 165mmx175mm. There's a gap between the lid and the stirofoam layer of 8mm.

**Comment by AljazKrsnik** [comment]
Can you send me/show me the shape of the top plate that they have already made 100 pcs?

**Comment by JanezCim** [comment]
the top plate that they already made is the standard top plate that was a part of the robot until now. I cant find a picture or a 3d model of it anywhere right now. 

Its the same top toplate that you were modifying here https://github.com/UbiquityRobotics/magni_robot/issues/184 but without the lidar, cable or the screen holes

**Comment by AljazKrsnik** [comment]
Ok. Thx

V pet., 5. nov. 2021 11:06 je oseba Janez Cimerman ***@***.***>
napisala:

**Comment by AljazKrsnik** [comment]
![lider mount](https://user-images.githubusercontent.com/87651656/141687443-0fa9275f-01ee-4555-8e28-8ad6e66034d0.PNG)
![lider moun2](https://user-images.githubusercontent.com/87651656/141687447-9ae866f6-f974-4c07-b1b9-d36680d93355.PNG)

Here is a mount. If i understood you correctly there is only 8 mm of free space in height?
With this mount, we are gonna have same lider position( latest). I can also make aditional holes for the new lidar?
We must ask Petal pečnik if he can make thak kind of part becouse of small amount of material on the curwin point.

**Comment by JanezCim** [comment]
@AljazKrsnik if I understand correctly that green mount is made to fit onto the Top Plate (gray) right? This mount is meant as a replacement for the top plate, and does not actually need to sorround it. So i would maybe rather do it as a simple plate (shape is already nice) - without any bending parts. Maybe it'll be quicker if we discuss this on a call

**Comment by AljazKrsnik** [comment]
I see. That is a bit different. So we make a holder like this? Or if we really need stifness becouse of the LIDAR, we can make 2 mm thick sheet metal and i think that it would be suficient? Dont know the weight of the lidar...
For the mounting we can chanfer the holes( than we must go with al least 2 mm), or we can bolt it and use other emtpy holes.
![LIDAR MOUNT](https://user-images.githubusercontent.com/87651656/141831814-25472284-d906-49d5-ae10-96d8f1b8e27a.PNG)
![LIDAR MOUNT2](https://user-images.githubusercontent.com/87651656/141831822-4776488d-b776-4c71-bde3-7ad1205d847d.PNG)

**Comment by JanezCim** [comment]
Yes that looks better then before. Do you think chanfering is absolutely needed since it adds complexity to the production process?

I also dont know the weight of the lidar sory. But you can also make this from 3mm aluminium since that is how thick the top plate is anyway.

Just one more thing to note, after we have made some test units of this plate for us at Pečniks place and tested them, we will try to produce the rest of them at our production contact in China - since these need to be shipped to our lidar suplier which is also in china. This is so we try to avoid tarifs and very long shipping time

**Comment by AljazKrsnik** [comment]
No problem. I will make it without chanfering.

**Comment by JanezCim** [comment]
@AljazKrsnik  Is this part ready to be produced then after we've tested it in TP? If yes, can you point me to the correct file on Zoho?

**Comment by JanezCim** [comment]
Oh and also on the test units in TP dont have these holes. That may be good to be added to that design.

![image](https://user-images.githubusercontent.com/8426792/146153762-cc57cd6d-437a-4d8c-93d5-2f110cc12150.png)

**Comment by JanezCim** [comment]
@AljazKrsnik can you send a zoho link to the file which i can send to production for this temporary lidar mount if its ready for production?

**Comment by AljazKrsnik** [comment]
Will send today( evening hours).

V V tor., 21. dec. 2021 ob 11:15 je oseba Janez Cimerman <
***@***.***> napisala:

**Comment by AljazKrsnik** [comment]
Here is the new, updated mount with aditional holes.
https://workdrive.zohoexternal.com/external/2c910607cb649df274d970fb7bda6b4dd066c89eb6d7f333686d835c7470af84

**Comment by JanezCim** [comment]
temporary mounts from Leishen are in slovenia, now we need to test them:
 - is colored blue RGB(48, 94, 177) - is it colored or annodized?
 - Each sample unit should come with 4xM3x8mm Cap socket screws.  - is this true?
 - mount on robot and mount ls lidar on it - does everything fit?
 - mount ld lidar on it - does it fit? 
 - how many mounts have arrived - should be 10?

@GreTimotej once you test this please message this to Neja and she is going to organise sending of mounts to customers. Also message here if all test are good so i can message stephen that we have a green light for more.

**Comment by GreTimotej** [comment]
After today's tests:
- The piece is colored blue, but a bit darker than RGB(48, 94, 177). At least that is how it looks compared to the color viewed on the computer. It is anodized, ([See pictures here](https://workdrive.zohoexternal.com/folder/qc97hc5bc2475baac4825bf6137adce9526ca)).
- Alongside the 10 mounts we also got 40 M3x8mm Cap socket screws. That is 4 screws per piece. They were also measured and I can confirm that they are 8mm long.
- The mount can be mount on the robot, but one of the holes is a bit wrong. The screw can not be put in all the four holes, because of the tension against one side([see picture](https://workdrive.zohoexternal.com/folder/qc97he347ff9d83084fda85976063fd102145), how the screw has less space on right side of the hole than on the left side). The same if with all the other holes.
- LS Lidar can be mount - it fits good. One small thing I noticed is that the screw thread is a bit poorly cut and the screws are sometimes a bit hard to screw into the thread. ([see pictures](https://workdrive.zohoexternal.com/folder/qc97hed2bfc65074e41ada23cea8dad387867)) here
- LD Lidar does fit, but the screw thread issue applies here too. ([see pictures here](https://workdrive.zohoexternal.com/folder/qc97hbca8d0b8af7c4504b3ef5464ffd9ece5))

**Comment by AljazKrsnik** [comment]
I will look the 3d files if the holes are concentric or not and report
today( majbe 3d file wrong or press in nuts inserted at an angle)
Is the lidar stable with just 2 screws( as planed)?
Does the lidar( sheet metal) oscilate or shake when MAGNI moves?

V V čet., 17. mar. 2022 ob 12:39 je oseba Timotej Gregorič <
***@***.***> napisala:

**Comment by GreTimotej** [comment]
@AljazKrsnik Yes the Lidar is stable with just 2 screws and when Magni is moving everything is still (Mount mounted with 2 screws and LS Lidar also mounted with 2 screws).

**Comment by AljazKrsnik** [comment]
Hi. The MAGNI 5 has only 3 inserts on FRONT SUPPORT( number 6 -https://workdrive.zoho.com/home/g9vop387248f4f5304dde876eb982824d88c5/teams/g9vop387248f4f5304dde876eb982824d88c5/ws/g9vop0ead768c4254422e9332d4e4fd4a414b/folders/ktgta31e7040cc0d64d23a41dfc5f4eac3ead). Look the link.

Here is another picture for this LIDAR mount.
![COAKSIAL HOLES](https://user-images.githubusercontent.com/87651656/159187200-b195f7f7-237d-4194-8dd4-689ca8b82aa6.GIF)
I looked my files and the holes are coaksial. I would look just the holes made in the sheet metal, and check if they are really coaksial( if they have the latest files). Or the inserts are not coaksial inserted. 

When putting in the screws, do NOT fully tighten them. Screw all in but fully tighten them when all are almost fully tightened.

**Comment by anfederman** [comment]
My top plate has the holes for top center.

**Comment by JanezCim** [comment]
@anfederman yes, you got top plate that was ment only for testing. The top plates and temporary plates in all the future builds will have the lidar holes slightly offset to robots right

**Comment by JanezCim** [comment]
@GreTimotej I have to answer to the producer of these holders, what is the status now of this? Are the holes coaxial then and can i give a green light for producing more holders OR do we have to do another iteration?

**Comment by GreTimotej** [comment]
@JanezCim yes, sorry. The holes are coaxial and you can give the green light for the production.

**Comment by JanezCim** [comment]
Great, thanks!

**Comment by anfederman** [comment]
Ok does that mean we need to modify the laser filter yaml and static
transform for various configurationd?

**Comment by AljazKrsnik** [comment]
Will the small lidar mounting holes need adjustment?

V V čet., 17. mar. 2022 ob 13:02 je oseba Timotej Gregorič <
***@***.***> napisala:
