### ISSUE TITLE
Styrophome Packaging 3D Standard work instructions

### ISSUE THREAD

**Issue by JanezCim** [UbiquityRobotics/magni_robot#192]
@AljazKrsnik I've got 3D files for **new syrophome packaging**: https://workdrive.zoho.com/folder/8x05cf73c06f4f97648cb94343140f18889a3

What we need to do it update the magni standard work instructions with the new packaging: https://writer.zoho.com/writer/open/456pt0c2a3e68e60e4804b0d4b084b3294656

Specifically, import these into solidworks, insert magni, create screenshots, insert screenshots into standard work

**Comment by AljazKrsnik** [comment]
Cannot open. Can files be saved in step file? I cannot open them.

**Comment by MoffKalast** [comment]
![Untitled](https://user-images.githubusercontent.com/9977799/151158197-5a1faaa3-7999-4b10-911c-5e268537afe1.jpg)

**Comment by AljazKrsnik** [comment]
:D

V V sre., 26. jan. 2022 ob 12:49 je oseba MoffKalast <
***@***.***> napisala:

**Comment by JanezCim** [comment]
@AljazKrsnik I will ask the guy in the mail and include you

**Comment by AljazKrsnik** [comment]
I am working on package assembly. But i am a bit confused. I do not know where to use top sides? It seems that the whole package assembly is kinda ok without 
![PACKAGE2](https://user-images.githubusercontent.com/87651656/151444048-f4e33c85-b408-42da-851a-e33de94db4b7.GIF)
![PACKAGE3](https://user-images.githubusercontent.com/87651656/151444051-a38a0183-01e1-44d4-8210-47dbd08556c6.GIF)
![PACKAGE4](https://user-images.githubusercontent.com/87651656/151444055-6e5b1390-ac0b-4846-b709-6e4599e3267e.GIF)
![PACKAGE1](https://user-images.githubusercontent.com/87651656/151444056-ab73c73e-94ec-428b-8500-74a075b7ba9f.GIF)
"top sides" part.

**Comment by JanezCim** [comment]
yeah looks wierd. Can you ask Vasyl on mail about it?

**Comment by JanezCim** [comment]
Btw look at magni standard work step 71. I think they Vasyl forgot to add a piece of styrophome that would fit here 
![bla](https://user-images.githubusercontent.com/8426792/151521792-8833e789-2296-4f78-b175-63af0cfd4948.png)

Do you see that also from the 3d model?

For current units the manufacturer is creating the missing piece from bubblewrap and there have been complains about the part missing. When you send a mail to Vasyl, be sure to include me so i can tell him this.

**Comment by AljazKrsnik** [comment]
Ok. Will ask him for more info.

V V pet., 28. jan. 2022 ob 10:30 je oseba Janez Cimerman <
***@***.***> napisala:

**Comment by JanezCim** [comment]
Any progress on this?

**Comment by AljazKrsnik** [comment]
Yes. Will do this first. Got the mail from vasily, how to pack all together.

V tor., 1. feb. 2022 16:06 je oseba Janez Cimerman ***@***.***>
napisala:

**Comment by AljazKrsnik** [comment]
HI

I have made 3D catalogue for styrophome packaging. Tell me what you think. 
[MAGNI 5 WITH PACKAGE.PDF](https://github.com/UbiquityRobotics/magni_robot/files/8015110/MAGNI.5.WITH.PACKAGE.PDF)

I have renamed some ofthe packaging files( more user friendly)

**Comment by AljazKrsnik** [comment]
I finally got the right files. And it matches the design. The file is on
github.

V V tor., 1. feb. 2022 ob 16:19 je oseba aljaz krsnik <
***@***.***> napisala:

**Comment by JanezCim** [comment]
Great! thanks @AljazKrsnik i've added the file to the standard work. If it does not present too much work for you, could you also recreate steps 68-83 with rendered images and try to replace them in the magni standard work:
https://writer.zoho.com/writer/open/456pt0c2a3e68e60e4804b0d4b084b3294656
Zoho editor is pretty crappy so if you dont want to deal with that, you can alternatevely just send me the pics and i can insert them

**Comment by AljazKrsnik** [comment]
![todo](https://user-images.githubusercontent.com/87651656/153205530-8a679cda-c4cc-436b-8cf9-784808b9d5c7.GIF)

What is here missing?

**Comment by AljazKrsnik** [comment]
![todo1](https://user-images.githubusercontent.com/87651656/153205768-339f8abd-e14a-42b1-96f1-faf3e494a3ae.GIF)

Is this FOAM  insert still present? Do i include it in assembly mauna?

**Comment by AljazKrsnik** [comment]
https://writer.zoho.com/writer/open/456pt0c2a3e68e60e4804b0d4b084b3294656

I have created new version. There are instructions for the new packaging system. The only thin i am not sure is about INSER FOAM on the upper picture. Will this still be a part of the new packaging assembly?

**Comment by JanezCim** [comment]
> What is here missing?

This: https://github.com/UbiquityRobotics/ubiquity_main/issues/255 david needs to arrange with lee pulver that we get updated certificates of conformance.

> Is this FOAM insert still present? Do i include it in assembly mauna?

I think yes, its still present

**Comment by JanezCim** [comment]
@AljazKrsnik the syrophome packaging for this is in standard work already and done righ? If yes, you can close this issue with the button underneath :)
