### ISSUE TITLE
lidar false-detects robot in gazebo

### ISSUE THREAD

**Issue by JanezCim** [UbiquityRobotics/magni_robot#200]
running `roslaunch magni_gazebo empty_world.launch` in latest noetic-devel

![image](https://user-images.githubusercontent.com/8426792/159667413-6d605d80-243c-4c65-8693-d47aaf136678.png)

**Comment by JanezCim** [comment]
found out that commenting out sensor-hc-sr04 sensor dae files solves the problem 
https://github.com/UbiquityRobotics/magni_robot/blob/cfb8f85852e54119f8eda4ff8be8f6d91a0341cf/magni_description/urdf/sensors/sonar_hc-sr04.xacro#L18

so probably the dae file is the problem, wed have to change it. Anyway, a quickfix for this if you dont need sonars is to set the sonars to false

https://github.com/UbiquityRobotics/magni_robot/blob/cfb8f85852e54119f8eda4ff8be8f6d91a0341cf/magni_gazebo/launch/empty_world.launch#L17

**Comment by MoffKalast** [comment]
Hmm right, I think we had this issue before, but I can't recall what the fix was (or if there was any). There's probably an issue logged somewhere about it.

**Comment by JanezCim** [comment]
yeah i remember this as well but could not find it...

**Comment by JanezCim** [comment]
So a bit of experimentation and this is what I have:

if sonars have a colission box, the lidar detects it even though the colision boxes are not in the direct fov of the lidar:

![image](https://user-images.githubusercontent.com/8426792/160419179-379bb0f1-09f2-4d9b-b3cc-b88fb0b4b011.png)
 
as soon as i remove the colisions on sonar sensors the lidar works fine. I have zero clue what could be causing this, my best guess is some gazebo internal error?

Anyway I think having colisions on sonars is useless anyways so i would simply disable it, comment why its disabled and be done with it
