### ISSUE TITLE
Magnigazebo/launch/rviz_config.rviz

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/magni_robot#207]
The current rviz_config.rviz in magni_gazebo launch doesn't parse the urdf correctly. The breadcrumb_gazebo/launch/rviz_config.rviz
is correct, so if someone would be so kind to test this and copy the file over, I would appreciate it.

**Comment by MoffKalast** [comment]
The difference is that the gazebo one also launches magni_description, which solves the problem of the missing robot model.

**Comment by JanezCim** [comment]
@anfederman did @MoffKalast anwer your question? If yes, can you close the issue?

**Comment by MoffKalast** [comment]
Well we should find a way to solve this eventually, right now my workaround is to just launch magni_description separately which does work but also publishes duplicate transforms which causes other problems. We probably just need to add the model publisher or something, I haven't really looked into it.

**Comment by anfederman** [comment]
I got it working.
