### ISSUE TITLE
Is there a planned support for ROS2 on the magni robot?

### ISSUE THREAD

**Issue by PranavDhulipala** [UbiquityRobotics/magni_robot#218]

**Comment by MoffKalast** [comment]
Planned yes, but it'll be a while before we get there. ARM64 support needs to be sorted first.

**Comment by anfederman** [comment]
https://drive.google.com/file/d/1Hy1l9_HZpCfOumb3drOqLhoRBq3FKcW6/view?usp=share_link

Shows ARM 64 Noetic(Ubuntu 20.04) running just fine.

ROS2 will take a lot longer to convert for Magni,  however the Raspberry PI 4 ROS Humble RTOS ARM64 seem to work OK even with the Raspicam.

**Comment by anfederman** [comment]
Closing for now.
