### ISSUE TITLE
teleop_twist_keyboard not installed

### ISSUE THREAD

**Issue by jrlandau** [UbiquityRobotics/magni_robot#42]
rosrun teleop_twist_keyboard teleop_twist_keyboard.py  results in package teleop_twist_keyboard not found.

**Comment by jrlandau** [comment]
ubuntu@ubiquityrobot:~$ rosrun teleop_twist_keyboard teleop_twist_keyboard.py
[rospack] Error: package 'teleop_twist_keyboard' not found

**Comment by rohbotics** [comment]
This is an issue with the image which doesn't have teleop_twist_keyboard installed.

**Comment by rohbotics** [comment]
This is fixed on the current beta image (not yet released, needs more work).

**Comment by rohbotics** [comment]
Solved in 2017-11-12 image
