### ISSUE TITLE
Battery Voltage topic not visible on latest image

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/magni_robot#43]
The latest image doesn't seem to publish a battery voltage topic. I see the following topics:

/cmd_vel
/diagnostics
/joint_states
/joy
/left_error
/motor_node/parameter_descriptions
/motor_node/parameter_updates
/right_error
/rosout
/rosout_agg
/tf
/tf_static
/ubiquity_velocity_controller/odom

Nothing that looks like a batt_voltage.

**Comment by rohbotics** [comment]
Solved by 0.6.0 release of ubiquity_motor, which is waiting for sync.

**Comment by rohbotics** [comment]
This is fixed on the current beta image (not yet released, needs more work).

**Comment by rohbotics** [comment]
Solved in 2017-11-12 image
