### ISSUE TITLE
ros-kinetic-magni-robot package broken

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/magni_robot#55]
When I type `sudo apt install ros-kinetic-magni-robot` it doesn't work!!
Fails with following error:

The following packages have unmet dependencies:
 ros-kinetic-magni-robot : Depends: ros-kinetic-magni-demos but it is not going to be installed
                           Depends: ros-kinetic-magni-nav but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by rohbotics** [comment]
Yes i noticed this while trying to do an image build. 

I did a backport to try and fix it, run `sudo apt update` and try it again.

**Comment by rohbotics** [comment]
resolved
