### ISSUE TITLE
Robot starts, but doesn't stop, driving in various situations (Regression)

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/magni_robot#59]
We've found that in the new image - certain behaviors are problematic. In particular when we give it a voice command to "go forward 10cm" it starts driving forward but never stops. We've also noticed that if we set a waypoint and tell it to go to it - it will start driving but never stop.

If we do this in a robot that doesn't have a camera in it (and thus cannot see the fiducials) it doesn't seem to have any trouble driving forward 10 cm and then stopping, but this is not the behavior if fiducials are seen.

**Comment by jim-v** [comment]
Suggest using `rostopic` to check that the odometry is working and that `move_basic` is subscribed to the correct topic.  A second suggestion is to have `move_basic` abort goals if odometry does not indicate progress towards them.

**Comment by jim-v** [comment]
Please disregard my previous comment.  My suggestion is to view use rviz to determine if the robot is moving in the expected direction.  If it is moving backwards with respect to the map frame in rviz, then the camera is not mounted consistently with the way it is specified in the URDF.

**Comment by rohbotics** [comment]
Is this still a bug? Or was it a firmware issue?
