### ISSUE TITLE
Should have a breaker to cut all power of the system

### ISSUE THREAD

**Issue by pyhuang2011** [UbiquityRobotics/magni_robot#80]
according to regulation,
recommend: https://jp.misumi-ec.com/vona2/detail/222000381211/?HissuCode=NF32-SV%202P%2020A&PNSearch=NF32-SV%202P%2020A&KWSearch=NF32-SV%202P%2020A&searchFlow=results2products

**Comment by pyhuang2011** [comment]
it is from IEC 60204-1 (JIS B9960-1) 5.3
if ECB can also cut all power, it is fine to me, but I think in this case, spark should not be there when connect a battery

**Comment by anfederman** [comment]
old, done on conveyor bot
