### ISSUE TITLE
Unable to add WiFi connections under pifi

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/magni_robot#89]
When I try the following I get the as shown errors.

ubuntu@ubiquityrobot:~$ sudo pifi set-hostname rachel
[sudo] password for ubuntu: 
Changing hostname from rachel to rachel
ubuntu@ubiquityrobot:~$ sudo pifi add ActualWifiremoved  XXXXXXXXpasswordremovedXXXXX
sudo: unable to resolve host rachel: Connection refused
ubuntu@ubiquityrobot:~$ sudo pifi add ActualWifiremoved [XXXXXXXXpasswordremovedXXXXX]
sudo: unable to resolve host rachel: Connection refused

**Comment by rohbotics** [comment]
Those sudo errors are safely ignoreable, it is a result of setting the hostname first.
