### ISSUE TITLE
Downfacing camera pose (Rotation)

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/magni_robot#98]
The 20 degree downfacing new camera bracket and the full forward camera mount both need to have proper pose worked out and supported in the magni_description/urdf/magni.urdf.xacro file

**Comment by mjstn** [comment]
The two new pose values have been worked out with names of 'downward' for the 20 deg down mount and 'ahead' for the straight ahead new camera hardware on new chassis iteration. 
We still need to push these and then take actions so the next image has support built in.
